/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import audios.AePlayWave;
import audios.PlayAudio;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;


/**
 *
 * @author Usuario
 */
public class Memorama extends javax.swing.JFrame {

    private int tiro;//numero de tiros
    private int pos1;//posicion tiro 1
    private int pos2;//posicion tiro 2
    private String[] imagenes= new String[24];
    private JButton[] tarjetas = new JButton[24]; //arreglo donde se almacenan las tarjetas principales
    private boolean[] volteadas = new boolean[24];
    private boolean turnoJ1 = true;
    private int pares1; //declaracion de la variable que almacena el numero de pares del jugador 1
    private int pares2; //declaracion de la variable que almacena el numero de pares del jugador 2
    
    
    /**
     * Creates new form Memorama
     */
    public Memorama() {
        initComponents();
        centrarForma();
        bloquear();
        iniTarjetas();
    }
    
    private void iniTarjetas(){
        tarjetas[0] = btnTarj1;
        tarjetas[1] = btnTarj2;
        tarjetas[2] = btnTarj3;
        tarjetas[3] = btnTarj4;
        tarjetas[4] = btnTarj5;
        tarjetas[5] = btnTarj6;
        tarjetas[6] = btnTarj7;
        tarjetas[7] = btnTarj8;
        tarjetas[8] = btnTarj9;
        tarjetas[9] = btnTarj10;
        tarjetas[10] = btnTarj11;
        tarjetas[11] = btnTarj12;
        tarjetas[12] = btnTarj13;
        tarjetas[13] = btnTarj14;
        tarjetas[14] = btnTarj15;
        tarjetas[15] = btnTarj16;
        tarjetas[16] = btnTarj17;
        tarjetas[17] = btnTarj18;
        tarjetas[18] = btnTarj19;
        tarjetas[19] = btnTarj20;
        tarjetas[20] = btnTarj21;
        tarjetas[21] = btnTarj22;
        tarjetas[22] = btnTarj23;
        tarjetas[23] = btnTarj24;
    }

    private void centrarForma() {

        //Dimension de la pantalla ANCHO Y ALTO
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        //Dimension de la ventana
        Dimension ventana = this.getSize();
        //posicion del borde superior izquierdo de la pantalla
        double posX = (pantalla.getWidth() - ventana.getWidth()) / 2.0;
        double posY = (pantalla.getHeight() - ventana.getHeight()) / 2.0;

        //Establece la posicion
        this.setLocation((int) posX, (int) posY);
    }

    private void solicitarJugador() { //metodo para preguntar y almacenar los valores (los nombres) de los jugadores
        String j1 = JOptionPane.showInputDialog("Nombre del primer jugador "); //me pide el nombre del primer jugador
        txtJugador1.setText(j1);// lo almacena en la caja de texto
        String j2 = JOptionPane.showInputDialog("Nombre del segundo jugador ");//me pide el nombre del segundo jugador
        txtJugador2.setText(j2);//lo almacena el el txt
        
        if( j1.isEmpty() | j2.isEmpty() ){ //en caso de que cualquiera de los campos no haya sido llenado
            JOptionPane.showMessageDialog(null, "Ingresa los jugadores correctamente"); //manda mensaje de advertencia
            reiniciar(); // manda llamar al metodo para reiniciar el juego
        }

    }

    
    private void Inicializardate() { //metodo que va a inicializar todos los datos
        tiro=0;
        turnoJ1=true;
        pares1=0;
        pares2=0;
        for(int i=0; i<24; i++){
            volteadas[i]=false; //pondra todas las cartas disponibles
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnTarj1 = new javax.swing.JButton();
        btnTarj2 = new javax.swing.JButton();
        btnTarj3 = new javax.swing.JButton();
        btnTarj4 = new javax.swing.JButton();
        btnTarj5 = new javax.swing.JButton();
        btnTarj6 = new javax.swing.JButton();
        btnTarj7 = new javax.swing.JButton();
        btnTarj8 = new javax.swing.JButton();
        btnTarj9 = new javax.swing.JButton();
        btnTarj10 = new javax.swing.JButton();
        btnTarj11 = new javax.swing.JButton();
        btnTarj12 = new javax.swing.JButton();
        btnTarj13 = new javax.swing.JButton();
        btnTarj14 = new javax.swing.JButton();
        btnTarj15 = new javax.swing.JButton();
        btnTarj16 = new javax.swing.JButton();
        btnTarj17 = new javax.swing.JButton();
        btnTarj18 = new javax.swing.JButton();
        btnTarj19 = new javax.swing.JButton();
        btnTarj20 = new javax.swing.JButton();
        btnTarj21 = new javax.swing.JButton();
        btnTarj22 = new javax.swing.JButton();
        btnTarj23 = new javax.swing.JButton();
        btnTarj24 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        listCat = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblJ2 = new javax.swing.JLabel();
        txtJugador2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblJ1 = new javax.swing.JLabel();
        txtJugador1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblCount1 = new javax.swing.JLabel();
        lblCount2 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(820, 640));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setMaximumSize(new java.awt.Dimension(800, 100));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 100));

        jLabel1.setBackground(new java.awt.Color(153, 255, 204));
        jLabel1.setForeground(new java.awt.Color(102, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/memT.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 100));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ll.jpg"))); // NOI18N
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ll.jpg"))); // NOI18N
        jLabel8.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel6.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel6.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel6.setLayout(new java.awt.GridLayout(4, 6));

        btnTarj1.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj1.setBorderPainted(false);
        btnTarj1.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj1.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj1MouseExited(evt);
            }
        });
        btnTarj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj1);

        btnTarj2.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj2.setBorderPainted(false);
        btnTarj2.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj2.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj2MouseExited(evt);
            }
        });
        btnTarj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj2);

        btnTarj3.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj3.setBorderPainted(false);
        btnTarj3.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj3.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj3MouseExited(evt);
            }
        });
        btnTarj3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj3ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj3);

        btnTarj4.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj4.setBorderPainted(false);
        btnTarj4.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj4.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj4MouseExited(evt);
            }
        });
        btnTarj4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj4ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj4);

        btnTarj5.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj5.setBorderPainted(false);
        btnTarj5.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj5.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj5MouseExited(evt);
            }
        });
        btnTarj5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj5ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj5);

        btnTarj6.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj6.setBorderPainted(false);
        btnTarj6.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj6.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj6MouseExited(evt);
            }
        });
        btnTarj6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj6ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj6);

        btnTarj7.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj7.setBorderPainted(false);
        btnTarj7.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj7.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj7MouseExited(evt);
            }
        });
        btnTarj7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj7ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj7);

        btnTarj8.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj8.setBorderPainted(false);
        btnTarj8.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj8.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj8MouseExited(evt);
            }
        });
        btnTarj8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj8ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj8);

        btnTarj9.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj9.setBorderPainted(false);
        btnTarj9.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj9.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj9MouseExited(evt);
            }
        });
        btnTarj9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj9ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj9);

        btnTarj10.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj10.setBorderPainted(false);
        btnTarj10.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj10.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj10MouseExited(evt);
            }
        });
        btnTarj10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj10ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj10);

        btnTarj11.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj11.setBorderPainted(false);
        btnTarj11.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj11.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj11MouseExited(evt);
            }
        });
        btnTarj11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj11ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj11);

        btnTarj12.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj12.setBorderPainted(false);
        btnTarj12.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj12.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj12MouseExited(evt);
            }
        });
        btnTarj12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj12ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj12);

        btnTarj13.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj13.setBorderPainted(false);
        btnTarj13.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj13.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj13MouseExited(evt);
            }
        });
        btnTarj13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj13ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj13);

        btnTarj14.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj14.setBorderPainted(false);
        btnTarj14.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj14.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj14MouseExited(evt);
            }
        });
        btnTarj14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj14ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj14);

        btnTarj15.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj15.setBorderPainted(false);
        btnTarj15.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj15.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj15MouseExited(evt);
            }
        });
        btnTarj15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj15ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj15);

        btnTarj16.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj16.setBorderPainted(false);
        btnTarj16.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj16.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj16MouseExited(evt);
            }
        });
        btnTarj16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj16ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj16);

        btnTarj17.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj17.setBorderPainted(false);
        btnTarj17.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj17.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj17MouseExited(evt);
            }
        });
        btnTarj17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj17ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj17);

        btnTarj18.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj18.setBorderPainted(false);
        btnTarj18.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj18.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj18MouseExited(evt);
            }
        });
        btnTarj18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj18ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj18);

        btnTarj19.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj19.setBorderPainted(false);
        btnTarj19.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj19.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj19MouseExited(evt);
            }
        });
        btnTarj19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj19ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj19);

        btnTarj20.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj20.setBorderPainted(false);
        btnTarj20.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj20.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj20MouseExited(evt);
            }
        });
        btnTarj20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj20ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj20);

        btnTarj21.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj21.setBorderPainted(false);
        btnTarj21.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj21.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj21MouseExited(evt);
            }
        });
        btnTarj21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj21ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj21);

        btnTarj22.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj22.setBorderPainted(false);
        btnTarj22.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj22.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj22MouseExited(evt);
            }
        });
        btnTarj22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj22ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj22);

        btnTarj23.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj23.setBorderPainted(false);
        btnTarj23.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj23.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj23MouseExited(evt);
            }
        });
        btnTarj23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj23ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj23);

        btnTarj24.setBackground(new java.awt.Color(204, 255, 255));
        btnTarj24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mira.jpg"))); // NOI18N
        btnTarj24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarj24.setBorderPainted(false);
        btnTarj24.setMaximumSize(new java.awt.Dimension(100, 12));
        btnTarj24.setPreferredSize(new java.awt.Dimension(100, 125));
        btnTarj24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarj24MouseExited(evt);
            }
        });
        btnTarj24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarj24ActionPerformed(evt);
            }
        });
        jPanel6.add(btnTarj24);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setMaximumSize(new java.awt.Dimension(200, 500));
        jPanel7.setMinimumSize(new java.awt.Dimension(200, 500));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 500));

        listCat.setFont(new java.awt.Font("Nyala", 0, 18)); // NOI18N
        listCat.setForeground(new java.awt.Color(102, 0, 0));
        listCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccion", "Shojo", "Gore" }));
        listCat.setToolTipText("Categoría");
        listCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCatActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Categoría");

        lblJ2.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        lblJ2.setText("JUGADOR 2:");

        txtJugador2.setFont(new java.awt.Font("Nyala", 2, 18)); // NOI18N
        txtJugador2.setForeground(new java.awt.Color(51, 0, 51));

        jLabel4.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PARES:");

        lblJ1.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        lblJ1.setText("JUGADOR 1:");

        txtJugador1.setFont(new java.awt.Font("Nyala", 2, 18)); // NOI18N
        txtJugador1.setForeground(new java.awt.Color(0, 51, 51));

        jLabel6.setFont(new java.awt.Font("Nyala", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PARES:");

        lblCount1.setFont(new java.awt.Font("Nyala", 2, 36)); // NOI18N
        lblCount1.setForeground(new java.awt.Color(153, 0, 0));
        lblCount1.setText("0");

        lblCount2.setFont(new java.awt.Font("Nyala", 2, 36)); // NOI18N
        lblCount2.setForeground(new java.awt.Color(153, 0, 0));
        lblCount2.setText("0");

        btnStart.setBackground(new java.awt.Color(255, 204, 255));
        btnStart.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        btnStart.setForeground(new java.awt.Color(102, 0, 0));
        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 204, 255));
        btnSalir.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(102, 0, 0));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 204, 255));
        btnReset.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(102, 0, 0));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJ1)
                    .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listCat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                            .addComponent(lblCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtJugador2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblJ2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listCat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCount1))
                .addGap(18, 18, 18)
                .addComponent(lblJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnSalir))
                .addGap(26, 26, 26)
                .addComponent(btnReset)
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reiniciar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
           btnTarj1.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj2.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj3.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj4.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj5.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj6.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj7.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj8.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj9.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj10.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj11.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj12.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj13.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj14.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj15.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj16.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj17.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj18.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj19.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj20.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj21.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj22.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj23.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
           btnTarj24.setIcon(new ImageIcon(getClass().getResource("/images/mira.jpg")));
        solicitarJugador();
        desBloquear();
        btnStart.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartActionPerformed

    private void listCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCatActionPerformed
        cambiarEstilo();
        cargarImagenes();
        Inicializardate();
        lblCount1.setText(""+pares1);
        lblCount2.setText(""+pares2);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_listCatActionPerformed

    private void btnTarj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj1ActionPerformed
        tirar(0); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj1ActionPerformed

    private void btnTarj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj2ActionPerformed
       
      tirar(1);       
// TODO add your handling code here:
    }//GEN-LAST:event_btnTarj2ActionPerformed

    private void btnTarj3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj3ActionPerformed
     
        tirar(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj3ActionPerformed

    private void btnTarj4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj4ActionPerformed
        
        tirar(3);
    // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj4ActionPerformed

    private void btnTarj5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj5ActionPerformed
       
        tirar(4);
// TODO add your handling code here:
    }//GEN-LAST:event_btnTarj5ActionPerformed

    private void btnTarj6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj6ActionPerformed
       
       tirar(5);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj6ActionPerformed

    private void btnTarj7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj7ActionPerformed
        tirar(6);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj7ActionPerformed

    private void btnTarj8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj8ActionPerformed
        tirar(7);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj8ActionPerformed

    private void btnTarj9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj9ActionPerformed
        tirar(8);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj9ActionPerformed

    private void btnTarj10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj10ActionPerformed
        tirar(9)   ;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj10ActionPerformed

    private void btnTarj11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj11ActionPerformed
    tirar(10);    
    // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj11ActionPerformed

    private void btnTarj12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj12ActionPerformed
       tirar(11); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj12ActionPerformed

    private void btnTarj13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj13ActionPerformed
        tirar(12); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj13ActionPerformed

    private void btnTarj14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj14ActionPerformed
        tirar(13); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj14ActionPerformed

    private void btnTarj15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj15ActionPerformed
        tirar(14); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj15ActionPerformed

    private void btnTarj16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj16ActionPerformed
        tirar(15); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj16ActionPerformed

    private void btnTarj17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj17ActionPerformed
       tirar(16); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj17ActionPerformed

    private void btnTarj18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj18ActionPerformed
        tirar(17);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj18ActionPerformed

    private void btnTarj19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj19ActionPerformed
       tirar(18);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj19ActionPerformed

    private void btnTarj20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj20ActionPerformed
       tirar(19);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj20ActionPerformed

    private void btnTarj21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj21ActionPerformed
        tirar(20);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj21ActionPerformed

    private void btnTarj22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj22ActionPerformed
        tirar(21);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj22ActionPerformed

    private void btnTarj23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj23ActionPerformed
        tirar(22);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj23ActionPerformed

    private void btnTarj24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarj24ActionPerformed
       tirar(23);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarj24ActionPerformed

    private void btnTarj1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj1MouseExited
        // TODO add your handling code here:
        
        evaluar();
        
        
    }//GEN-LAST:event_btnTarj1MouseExited

    private void btnTarj2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj2MouseExited
        // TODO add your handling code here:
        
        evaluar();
    }//GEN-LAST:event_btnTarj2MouseExited

    private void btnTarj3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj3MouseExited
        // TODO add your handling code here:
        
        evaluar();
    }//GEN-LAST:event_btnTarj3MouseExited

    private void btnTarj4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj4MouseExited
        // TODO add your handling code here:
        
        evaluar();
    }//GEN-LAST:event_btnTarj4MouseExited

    private void btnTarj5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj5MouseExited
        // TODO add your handling code here:
        
        evaluar();
    }//GEN-LAST:event_btnTarj5MouseExited

    private void btnTarj6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj6MouseExited
        // TODO add your handling code here:
        evaluar();
    }//GEN-LAST:event_btnTarj6MouseExited

    private void btnTarj7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj7MouseExited
        // TODO add your handling code here:
        evaluar();
    }//GEN-LAST:event_btnTarj7MouseExited

    private void btnTarj8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj8MouseExited
        // TODO add your handling code here:
        evaluar();
    }//GEN-LAST:event_btnTarj8MouseExited

    private void btnTarj9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj9MouseExited
        // TODO add your handling code here:
        evaluar();
    }//GEN-LAST:event_btnTarj9MouseExited

    private void btnTarj13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj13MouseExited
        // TODO add your handling code here:
        evaluar();
    }//GEN-LAST:event_btnTarj13MouseExited

    private void btnTarj10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj10MouseExited
        // TODO add your handling code here:
         evaluar();
    }//GEN-LAST:event_btnTarj10MouseExited

    private void btnTarj11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj11MouseExited
        // TODO add your handling code here:
         evaluar();
    }//GEN-LAST:event_btnTarj11MouseExited

    private void btnTarj12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj12MouseExited
        // TODO add your handling code here:
         evaluar();
    }//GEN-LAST:event_btnTarj12MouseExited

    private void btnTarj14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj14MouseExited
        // TODO add your handling code here:
         evaluar();
    }//GEN-LAST:event_btnTarj14MouseExited

    private void btnTarj15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj15MouseExited
        // TODO add your handling code here:
         evaluar();
    }//GEN-LAST:event_btnTarj15MouseExited

    private void btnTarj16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj16MouseExited
        // TODO add your handling code here:
         evaluar();
    }//GEN-LAST:event_btnTarj16MouseExited

    private void btnTarj17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj17MouseExited
        // TODO add your handling code here:
         evaluar();
    }//GEN-LAST:event_btnTarj17MouseExited

    private void btnTarj18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj18MouseExited
        // TODO add your handling code here:
         evaluar();
    }//GEN-LAST:event_btnTarj18MouseExited

    private void btnTarj19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj19MouseExited
        // TODO add your handling code here:
         evaluar();
    }//GEN-LAST:event_btnTarj19MouseExited

    private void btnTarj20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj20MouseExited
        // TODO add your handling code here:
         evaluar();
    }//GEN-LAST:event_btnTarj20MouseExited

    private void btnTarj21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj21MouseExited
        // TODO add your handling code here:
         evaluar();
    }//GEN-LAST:event_btnTarj21MouseExited

    private void btnTarj22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj22MouseExited
        // TODO add your handling code here:
                 evaluar();

    }//GEN-LAST:event_btnTarj22MouseExited

    private void btnTarj23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj23MouseExited
        // TODO add your handling code here:
                 evaluar();

    }//GEN-LAST:event_btnTarj23MouseExited

    private void btnTarj24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarj24MouseExited
        // TODO add your handling code here:
                 evaluar();

    }//GEN-LAST:event_btnTarj24MouseExited

    public void evaluar(){
        if (tiro==2){
            if(imagenes[pos1].equals(imagenes[pos2])){//tarjetas iguales
                if(turnoJ1){
                    pares1++;
                    lblCount1.setText(""+pares1);
                } else {
                  pares2++;
                  lblCount2.setText(""+pares2);
                }
            } else {
                switch(listCat.getSelectedIndex()){ 
                    case 0:
                        break;
                    case 1:
                        tarjetas[pos1].setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
                        tarjetas[pos2].setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
                        break;
                    case 2:
                        tarjetas[pos1].setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
                        tarjetas[pos2].setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
                }
              volteadas[pos1]=false;
              volteadas[pos2]=false;
              
              turnoJ1 = !turnoJ1;
              if(turnoJ1){
                  lblJ1.setForeground(new java.awt.Color(255,0,0));// cambia el color al jugador 1 que es quien empieza
                  lblJ2.setForeground(new java.awt.Color(0,0,0));
              } else {
                  lblJ1.setForeground(new java.awt.Color(0,0,0));
                  lblJ2.setForeground(new java.awt.Color(255,0,0));// cambia el color al jugador 2 que es quien empieza
              }
            }
          tiro = 0;
        }
      
      if ((pares1+pares2)==12) { // la condicion revisa que todas las tarjetas esten en true (volteadas)
          if(pares1>pares2){ //esta segunda condicion es para ver su el primer jugador es el ganador 
              JOptionPane.showMessageDialog(null, "You are Winner ^w^r : " + txtJugador1.getText()); //Manda un mensaje del ganador
              
              
      
    
              
          } else if (pares2 > pares1) { //en caso de que no entonces evaluara si el segundo jugador entonces es el ganadpr
              JOptionPane.showMessageDialog(null, "You are Winner ^w^r : " + txtJugador2.getText());
              
            
              
            } else { //en caso de que ambos tengan el mismo numero de pares sera declarado un empate
                JOptionPane.showMessageDialog(null, "Empate :v"); //en caso de empate me manda el mensaje
                }
          pares1 = 0; //me inicializa la variable del pares1 en 0
          pares2 = 0; //me inicializa la variable del pares2 en 0
          
          JOptionPane.showMessageDialog(null, "Juego Terminado"); 
            int YesOrNot = JOptionPane.showConfirmDialog(null, "JUEGO TERMINADO ¿Desea seguir juagndo?", "Salir", JOptionPane.YES_NO_OPTION);//me da la opcion de si deseo seguir jugando
            if (YesOrNot == 0) { //en caso de que si
            
                JOptionPane.showMessageDialog(null, "A JUGAR!!"); // me manda el mensaje
                this.setVisible(false); 
                Memorama.main(null);// me carga el juego de nuevo
                return;
                
            } else {
                System.exit(0); //en caso de que no, se sale y lo cierra
            }
          
          }
      
        
    }
    
    public void cambiarEstilo(){ //metodo para cambiar las imagenes
       String estilo= listCat.getSelectedItem().toString();
       //me pone las tarjetas disponibles
        btnTarj1.setEnabled(true);
        btnTarj2.setEnabled(true);
        btnTarj3.setEnabled(true);
        btnTarj4.setEnabled(true);
        btnTarj5.setEnabled(true);
        btnTarj6.setEnabled(true);
        btnTarj7.setEnabled(true);
        btnTarj8.setEnabled(true);
        btnTarj9.setEnabled(true);
        btnTarj10.setEnabled(true);
        btnTarj11.setEnabled(true);
        btnTarj12.setEnabled(true);
        btnTarj13.setEnabled(true);
        btnTarj14.setEnabled(true);
        btnTarj15.setEnabled(true);
        btnTarj16.setEnabled(true);
        btnTarj17.setEnabled(true);
        btnTarj18.setEnabled(true);
        btnTarj19.setEnabled(true);
        btnTarj20.setEnabled(true);
        btnTarj21.setEnabled(true);
        btnTarj22.setEnabled(true);
        btnTarj23.setEnabled(true);
        btnTarj24.setEnabled(true);
       
       if(estilo=="Shojo"){ // carga las imagenes de la categoria del shojo en cada boton 
           btnTarj1.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj2.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj3.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj4.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj5.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj6.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj7.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj8.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj9.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj10.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj11.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj12.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj13.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj14.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj15.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj16.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj17.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj18.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj19.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj20.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj21.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj22.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj23.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
           btnTarj24.setIcon(new ImageIcon(getClass().getResource("/images/cardkw.jpg")));
       }else{
           if(estilo=="Gore"){ // carga las imagenes de la categoria del Gore 
           btnTarj1.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj2.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj3.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj4.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj5.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj6.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj7.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj8.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj9.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj10.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj11.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj12.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj13.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj14.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj15.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj16.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj17.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj18.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj19.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj20.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj21.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj22.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj23.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           btnTarj24.setIcon(new ImageIcon(getClass().getResource("/images/calavera.jpg")));
           }
       }
    
    }
    
    
    public void bloquear() { // bloquea al inicio del juego las tarjetas
        btnTarj1.setEnabled(false);
        btnTarj2.setEnabled(false);
        btnTarj3.setEnabled(false);
        btnTarj4.setEnabled(false);
        btnTarj5.setEnabled(false);
        btnTarj6.setEnabled(false);
        btnTarj7.setEnabled(false);
        btnTarj8.setEnabled(false);
        btnTarj9.setEnabled(false);
        btnTarj10.setEnabled(false);
        btnTarj11.setEnabled(false);
        btnTarj12.setEnabled(false);
        btnTarj13.setEnabled(false);
        btnTarj14.setEnabled(false);
        btnTarj15.setEnabled(false);
        btnTarj16.setEnabled(false);
        btnTarj17.setEnabled(false);
        btnTarj18.setEnabled(false);
        btnTarj19.setEnabled(false);
        btnTarj20.setEnabled(false);
        btnTarj21.setEnabled(false);
        btnTarj22.setEnabled(false);
        btnTarj23.setEnabled(false);
        btnTarj24.setEnabled(false);
        txtJugador1.setEnabled(false); // tambien bloquea la caja de texto del jugador 1
        txtJugador2.setEnabled(false); // bloquea la caja de texto del jugador 2
        listCat.setEnabled(false); // pone el falso la lista de las categorias hasta de clic en el boton de start

    }
    
    public void desBloquear() { //metodo que desbloquea la lista de categorias y los txt donde se almacenan los nombres de los jugadores
       
        txtJugador1.setEnabled(false);
        txtJugador2.setEnabled(false);
        listCat.setEnabled(true);

    }
    

    public void reiniciar() { // metodo que me da acceso a un juego nuevo y resetea todo el juego

        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Juego Nuevo");
        Memorama.main(null);
        return;

    }

    
    public void cargarImagenes(){ // metodo que me carga las imagenes dependiendo de la seleccion en la lista de categorias
            switch (listCat.getSelectedIndex()){
                case 1://Shojo en caso de seleccionar el shojo se cargaran en cada uno de los botones las siguientes imagenes
                    for(int i = 0; i < 12; i++){ // se recorre un arreglo donde la condicion de i<12 me da la facilitacion para que las imagenes se dupliquen y acaparen todos los botones y asi se encuentren pares
                        imagenes[i]="/images/b" +(i+1)+".jpg"; // primeramente me carga las imagenes del 1 al 12 cargandolas desde el paquete images que empiecen con la letra b y el valor de i incrementa hasta el 12
                        imagenes[i+12]="/images/b" +(i+1)+".jpg"; // ahora me carga las imagenes desde que i es del 13 hasta el tope de los botones
                    }
                break;
                case 2://Gore en caso de seleccionar el gore se cargaran en cada uno de los botones las siguientes imagenes
                    for(int i = 0; i < 12; i++){
                        imagenes[i]="/images/a" +(i+1)+".jpg"; //dependiendo del arreglo se cargaran las imagenes con la letra a desde el paquete de images las cuales son 12
                        imagenes[i+12]="/images/a" +(i+1)+".jpg"; // se agregan las siguientes imagenes (las copias o el par) agregarando al valor actual el numero 12
                    }
                break;
            }
    
        mezclar(); //metodo que mezclara todas las cartas 
        for (int i = 0; i < 24; i++){ // recorre el arreglo
           //tarjetas[i].setIcon(new ImageIcon(getClass().getResource(imagenes[i])));
        }
    }
    
    
    public void mezclar(){ // metodo que me permite mezclar las imagenes con la clase random
        Random r=new Random();
        int x;
        int y;
        String tempo; //declaramos una variable tempo 
        for (int i = 1; i <=500; i++){ // el for me permite revolver las imagenes hasta 500 veces
            x = r.nextInt(24); // pone el en uso la variable r de random() hasta un tope que es 24
            y = r.nextInt(24);
            tempo = imagenes[x]; //la variable tempo almacenara a la variable x (la imagen)
            imagenes[x] = imagenes[y]; // la imagen x ahora se cambiara a donde esta la imagen y
            imagenes[y] = tempo; // para que no se pierda y, la variable tempo almacenara el valor de y que ahora es x
        }
    }
    
    public void tirar(int pos){
        
        if (volteadas[pos]==false){//tarjeta disponible
            volteadas[pos]=true;// marca que la tarjeta ya no esta disponibler ya que ha sido volteada
            tarjetas[pos].setIcon(new ImageIcon(getClass().getResource(imagenes[pos]))); 
            if(tiro==0){ //si la variable tiro es igual a 0 entonces
                pos1=pos; //me indica que la variable pos1 sera igual a la posicion de la tarjeta volteada
                
            }else{ // en caso de ser falso
                pos2=pos; //me indica que ña variable pos2 toma el valor de la posicion de la segunda tarjeta volteada
                
            }
            tiro++; //incrementa la variable tiro
            // me manda el audio cuando doy clic a alguna tarjeta
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audios/end.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
        
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Memorama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnTarj1;
    private javax.swing.JButton btnTarj10;
    private javax.swing.JButton btnTarj11;
    private javax.swing.JButton btnTarj12;
    private javax.swing.JButton btnTarj13;
    private javax.swing.JButton btnTarj14;
    private javax.swing.JButton btnTarj15;
    private javax.swing.JButton btnTarj16;
    private javax.swing.JButton btnTarj17;
    private javax.swing.JButton btnTarj18;
    private javax.swing.JButton btnTarj19;
    private javax.swing.JButton btnTarj2;
    private javax.swing.JButton btnTarj20;
    private javax.swing.JButton btnTarj21;
    private javax.swing.JButton btnTarj22;
    private javax.swing.JButton btnTarj23;
    private javax.swing.JButton btnTarj24;
    private javax.swing.JButton btnTarj3;
    private javax.swing.JButton btnTarj4;
    private javax.swing.JButton btnTarj5;
    private javax.swing.JButton btnTarj6;
    private javax.swing.JButton btnTarj7;
    private javax.swing.JButton btnTarj8;
    private javax.swing.JButton btnTarj9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblCount1;
    private javax.swing.JLabel lblCount2;
    private javax.swing.JLabel lblJ1;
    private javax.swing.JLabel lblJ2;
    private javax.swing.JComboBox<String> listCat;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
